name: Deploy to Tencent Lighthouse Server

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
    paths:
      - www/**     # 仅当 www 文件夹及其子目录或文件发生更改时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出最新代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 使用 rsync 将内容上传到服务器
    - name: Sync 'www' contents to server
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > id_ed25519_github_actions
        chmod 600 id_ed25519_github_actions
        # 配置 SSH，确保免密登录你的服务器
        echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

        rsync -avz --delete ./www/ ubuntu@42.192.134.42:~/Sites/adopapacc/www
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
