name: Deploy to Tencent Lighthouse Server

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
    paths:
      - www/**     # 仅当 www 文件夹及其子目录或文件发生更改时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: 执行 SSH Deploy Action
      - name: SSH Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: ${{ secrets.RSYNC_ARGS }} # rsync 的参数，确保文件更新同步
          SOURCE: ${{ secrets.SOURCE }} # 本地需要同步的文件夹
          REMOTE_HOST: ${{ secrets.HOST }} # 目标服务器的 IP 地址
          REMOTE_USER: ${{ secrets.USER }} # 用于连接服务器的用户名
          TARGET: ${{ secrets.TARGET }} # 服务器上的目标路径
